development:
  adapter: postgresql
  encoding: unicode
  database: app_test_development
  pool: 5
  timeout: 5000
  username: dariab
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: app_test_test
  pool: 5
  timeout: 5000
  username: dariab
  password:
